name: Testiranje projekta

on:
  push:
    branches:
      - main

jobs:
  preveri_skripte:
    name: Preveri skripte
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preveri skripte
        run: |
          touch napaka.txt
          if [ ! -f tests/test.sh ]; then
            echo "Napaka: Testna skripta tests/test.sh ne obstaja." >> napaka.txt
          fi
          if [ ! -f tests/test_expected.txt ]; then
            echo "Napaka: output (test_expected.txt) ne obstaja." >> napaka.txt
          fi
          if [ ! -f tests/test_input.txt ]; then
            echo "Napaka: input (test_input.txt) ne obstaja." >> napaka.txt
          fi

      - name: Shrani napako
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  izvedi_skripte:
    name: Izvedi skripte
    needs: preveri_skripte
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prenesi napako
        uses: actions/download-artifact@v4
        with:
          name: napaka
          path: .

      - name: Izvedi skripte
        run: |
          if [! -f napaka.txt ]; then
            chmod +x tests/test.sh
            ./tests/test.sh > output.txt
          fi