name: Na DockerHub

on:
  push:
    branches:
      - main # Se sproži ob vsakem pushu na vejo 'main'
jobs:
  deploy:
    name: Deploy aplikacije
    runs-on: self-hosted # Uporabi lokalno gostiteljsko okolje
    needs: [izvedi_skripte] # Ta se izvede šele, ko se drugi uspešno zaključi

    strategy:
      matrix:
        os: [ubuntu-latest]  # Uporabi najnovejšo različico Ubuntu-ja kot virtualno okolje
        version: [latest]  # Uporabi najnovejšo različico Dockerja
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Potegne kodo iz repozitorija

      - name: Login na DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}| docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin # Prijava na DockerHub

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mojprojekt:latest . # Ustvari Docker sliko

      - name: Push na DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mojprojekt:latest # Potisni Docker sliko na DockerHub