name: Na DockerHub


on:
  workflow_run: # Triggered by another workflow
    workflows: ["Testiranje aplikacije"] # workflow to trigger tega
    types:
      - completed

jobs:
  deploy:
    name: Deploy aplikacije
    runs-on: self-hosted

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login na DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mojprojekt:latest .

      - name: Push na DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mojprojekt:latest
