name: Na DockerHub # Ime workflow-a

on:
  workflow_run:
    workflows: ["Testiranje projekta"]
    types:
      - completed # Ta workflow se sproži, ko se zaključi workflow "Testiranje projekta"
    

jobs:
  deploy:
    name: Deploy aplikacije # Ime opravila 
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Zaženi samo če je workflow uspešen
    runs-on: self-hosted # Ta job teče na self-hosted runnerju

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [latest] # Trenutno se uporablja samo 'latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Klonira repozitorij

      - name: Priprava okolja
        run: |  # Pripravi okolje
          echo "1"
          sudo apt-get update -y
          echo "2"
          sudo apt-get install -y docker.io
          echo "3"
          sudo systemctl start docker
          echo "4"
          sudo systemctl enable docker# Omogoči Docker, da se zažene ob zagonu sistema
          echo "5"

      - name: Login na DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin # Prijava v DockerHub

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/KMP:${{ matrix.version }} .  # Ustvari Docker sliko in jo označi  z imenom 'mojprojekt:latest'

      - name: Push na DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/KMP:${{ matrix.version }}  # Pošlje zgrajeno Docker sliko na DockerHub pod uporabniškim imenom
