name: Na DockerHub # Ime workflow-a

on:
  workflow_run:
    workflows: ["Testiranje projekta"]
    types:
      - completed # Ta workflow se sproži, ko se zaključi workflow "Testiranje projekta"

jobs:
  deploy:
    name: Deploy aplikacije # Ime opravila 
    runs-on: self-hosted # Ta job teče na self-hosted runnerju

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [latest] # Trenutno se uporablja samo 'latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Klonira repozitorij

      - name: Login na DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin # Prijava v DockerHub

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/KMP:${{ matrix.version }}  -f dockerfile .  # Ustvari Docker sliko in jo označi  z imenom 'mojprojekt:latest'

      - name: Push na DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/KMP:${{ matrix.version }}  # Pošlje zgrajeno Docker sliko na DockerHub pod uporabniškim imenom
